using NeonWarfare.Tests.Infrastructure;
using Xunit;

namespace NeonWarfare.Tests.Scenes;

/// <summary>
/// The files Godot keeps next to another file and for it: a <c>.uid</c> holding the identity of a script
/// or a shader, an <c>.import</c> holding the import settings of an asset. Docs/Code-style.md says they
/// are generated and must not be written by hand — which also means nobody notices when one goes missing
/// or stays behind.
/// </summary>
public class SidecarFileTests
{
    private const string UidExtension = ".uid";

    /// <summary>
    /// A .cs without its .uid gets a fresh one the next time the editor opens the project, and every
    /// scene that referenced the old one loses its script. The scenes still hold a <c>path=</c>, so it
    /// looks recoverable — but Godot resolves by uid and it is the uid that changed.
    /// </summary>
    [Theory]
    [MemberData(nameof(GameFileSources.Sources), MemberType = typeof(GameFileSources))]
    public void SourceFile_HasAUidSidecar(string relativePath)
    {
        string sidecar = relativePath + UidExtension;

        Assert.True(
            File.Exists(RepositoryPaths.Absolute(sidecar)),
            $"{relativePath}: {sidecar} is missing — it is generated by Godot and belongs in the commit");
    }

    /// <summary>
    /// The other direction: a sidecar left behind by a deleted file. It keeps a uid alive that points at
    /// nothing, which is exactly what makes a stale reference look valid.
    /// </summary>
    [Theory]
    [MemberData(nameof(GameFileSources.Sidecars), MemberType = typeof(GameFileSources))]
    public void Sidecar_HasTheFileItBelongsTo(string relativePath)
    {
        string owner = relativePath[..relativePath.LastIndexOf('.')];

        Assert.True(
            File.Exists(RepositoryPaths.Absolute(owner)),
            $"{relativePath}: {owner} does not exist — the sidecar outlived its file and should go too");
    }
}
