using NeonWarfare.RepoTests.Infrastructure;
using Xunit;

namespace NeonWarfare.RepoTests.Scenes;

/// <summary>
/// The files Godot keeps next to another file and for it: a <c>.uid</c> holding the identity of a script
/// or a shader, an <c>.import</c> holding the import settings of an asset. Docs/Code-style.md says they
/// are generated and must not be written by hand — which also means nobody notices when one goes missing
/// or stays behind.
/// </summary>
public class SidecarFileTests
{
    private const string UidExtension = ".uid";
    private const string ImportExtension = ".import";

    // The user regenerates the .uid files once in the editor after the network rework; task 025 restores the test.
    private const string SkipReason = "Muted during the network rework, see task 025-restore-sidecar-file-tests";

    /// <summary>
    /// A script or a shader without its .uid gets a fresh one the next time the editor opens the project,
    /// and every scene that referenced the old one loses it. The scenes still hold a <c>path=</c>, so it
    /// looks recoverable — but Godot resolves by uid and it is the uid that changed.
    /// </summary>
    [Theory(Skip = SkipReason)]
    [MemberData(nameof(FileSources.Sources), MemberType = typeof(FileSources))]
    [MemberData(nameof(FileSources.Shaders), MemberType = typeof(FileSources))]
    public void SourceFile_HasAUidSidecar(string relativePath) => AssertSidecarExists(relativePath, UidExtension);

    /// <summary>
    /// An imported asset keeps its uid in the .import, so a missing one is the same loss as a missing .uid,
    /// plus the import settings: the editor re-imports the asset with the defaults.
    /// </summary>
    [Theory(Skip = SkipReason)]
    [MemberData(nameof(FileSources.ImportedAssets), MemberType = typeof(FileSources))]
    public void Asset_HasAnImportSidecar(string relativePath) => AssertSidecarExists(relativePath, ImportExtension);

    /// <summary>
    /// The other direction: a sidecar left behind by a deleted file. It keeps a uid alive that points at
    /// nothing, which is exactly what makes a stale reference look valid.
    /// </summary>
    [Theory(Skip = SkipReason)]
    [MemberData(nameof(FileSources.Sidecars), MemberType = typeof(FileSources))]
    public void Sidecar_HasTheFileItBelongsTo(string relativePath)
    {
        string owner = relativePath[..relativePath.LastIndexOf('.')];

        Assert.True(
            File.Exists(RepositoryPaths.Absolute(owner)),
            $"{relativePath}: {owner} does not exist — the sidecar outlived its file and should go too");
    }

    private static void AssertSidecarExists(string relativePath, string extension)
    {
        string sidecar = relativePath + extension;

        Assert.True(
            File.Exists(RepositoryPaths.Absolute(sidecar)),
            $"{relativePath}: {sidecar} is missing — it is generated by Godot and belongs in the commit");
    }
}
